### ISSUE TITLE
Previously lagless maps now lag

### ISSUE THREAD

**Issue by JonBax** [SpookyThunder/Tortured-Planet#7]
Seems to be a nodebuilder issue. First noticed in **Sunshine Atoll Act 1**, then in **Gritty Columns Act 2**, both acts show severe drops in FPS after being tweaked in ZoneBuilder

**Comment by SpookyThunder** [comment]
its addedfolder

**Comment by JonBax** [comment]
Some more context: maps seem to lag when the mod is loaded through the `addfolder` command, but when compiled into a pk3 file through SLADE everything works out just fine

**Comment by SpookyThunder** [comment]
among us
